# SPDX-License-Identifier: MIT
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  enabled: false
platforms:
  - name: centos-7
    image: docker.io/linuxsystemroles/centos-7
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ../../tests/tests_default.yml
  lint:
    enabled: false
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - check
    - destroy
