---
- hosts: all
  become: true

  vars:
    certificate_requests:
      - name: mycert
        dns: www.example.com
        ca: self-sign
      - name: /tmp/other-cert
        dns: www.example.com
        ca: self-sign
      - name: /tmp/another-cert
        dns: www.example.com
        ca: self-sign

  roles:
    - certificate
