---
- hosts: all
  become: true

  vars:
    certificate_requests:
      - name: mycert
        dns: www.example.com
        ca: self-sign
        provider: fake-provider

  roles:
    - linux-system-roles.certificate
